### ISSUE TITLE
Root level ID in response holds subject ID, not patient ID

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-python#18]
Split from #16:

Some of the problem is likely also generated in how cda-client.py parse the results from BigQuery. For example, the root level id (which should be patient id) ends up holding the subject id in what is returned by cda-client.py. While the fix to the SQL above eliminates the duplication problem - there may be other issues arising from how cda-client.py turns the BigQuery results into Python objects and json.

Once #16 is resolved we can re-test and see if this problem is still present.

**Comment by ianfore** [comment]
Per what I saw for query6 [here](https://github.com/ianfore/cdatest/blob/main/SQL%20Exploration.ipynb ) am expecting that fixing the select *  will mean we get patient ids instead of subject ids.  So the issue in the title of this ticket should go away.

However, the root cause of it would still be there. As far as I can tell, has to do with how the REST API parses what it gets back from BigQuery. Better have another issue for that - but it probably belongs in cda-service. See https://github.com/CancerDataAggregator/cda-service/issues/67

**Comment by pshapiro4broad** [comment]
Thanks for the detailed issue, that will help a lot with testing. My fix for https://github.com/CancerDataAggregator/cda-service/issues/65 seems to address this when testing cda-service endpoint via swagger. I'll have to test it out with the python bindings and see what the results look like. I'm hoping the cda-service fix will be sufficient and cda-python won't need a change.

**Comment by pshapiro4broad** [comment]
I think this can be closed, the IDs are no longer overwritten by the boolean_query operation. The remaining issue with the JSON conversion when there are columns with duplicate names is covered in https://github.com/CancerDataAggregator/cda-service/issues/67
