### ISSUE TITLE
Add Imaging Data Commons to CDA

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#48]
Allow IDC to be indexed by CDA

**Comment by DavidPotCanuck** [comment]
Features include:

Features that are indexed and are searchable (ticket X)
Data that are returned and are searchable (ticket X or a new ticket Y

**Comment by druth314** [comment]
This is the mapping of fields currently supported by CDA. CDA field on the left, IDC field/value used on the right
{
"id":  "crdc_instance_uuid"
"associated_project": "collection_id"
"data_category": 'Imaging'
"data_type": "Modality"
"label": 'SUBSTR(gcs_url, 15)'
"byte_size": null
"checksum": 'NULL'
"file_format": 'DICOM'
"drs_uri": gcs_url
}
For clarification:
- data_category is the string 'Imaging' for all entries
- label uses a portion of the gcs_url. We use the SUBSTR() function in SQL to populate the field
- byte_size is a null integer type as no fields map from the IDC table we currently pull from
- checksum is a string NULL as no fields map from the IDC table we currently pull from
- file_format is the string 'DICOM' for all entries since all files in IDC are in DICOM format
- drs_uri is a misnomer, however identical schemas for File entities are required. As of now, there is no algorithmic way to construct drs_uri's from IDC data. Also the IDC data has not been indexed for drs_uri's

**Comment by elijahlowe** [comment]
IDC data is currently in CDA, the following code is an example case:
```
q = Q('id = "TCGA-13-1409"') # note the double quotes for the string value
r = q.run()

system = []

for patient in r:
    for file in patient['File']:
        for identifier in file['identifier']:
            system.append(identifier['system'])
    
print(set(system) )

{'IDC', 'PDC', 'GDC'}
```

**Comment by elijahlowe** [comment]
closing, see code above
