### ISSUE TITLE
File information will now be associated with Patient and Research Subject entities

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#51]
File information will now be associated with Patient and Research Subject entities

**Comment by DavidPotCanuck** [comment]
In release 1, file information was associated with ...

In release 2, file information will be associated also with Patient and Research Subject.

Outputs that users see of the file information are described in detail in this ticket (ticket x).

**Comment by YeastCell** [comment]
**R1 File entity**: **File** entity is only associated with **Specimen** entity. Additionally, only top level specimens of type _sample_ have non-empty **File** lists.
**R2 File entity**: **File** entity is associated with all three entities – **Specimen**, **ResearchSubject** and **Patient**, while all specimen types (portion, aliquot,...) contain corresponding files. (@druth314 please feel free to comment further as needed)

**R1 File fields and mappings**:
```
{
  "id": [
    {
      "PDC": "file_id",
      "GDC": "file_id"
    }
  ],
  "associated_project": [
    {
      "PDC": "project_submitter_id",
      "GDC": "project.project_id"
    }
  ],
  "data_category": [
    {
      "PDC": "data_category",
      "GDC": "data_category"
    }
  ],
  "data_type": [
    {
      "PDC": "file_type",
      "GDC": "data_type"
    }
  ],
  "label": [
    {
      "PDC": "file_name",
      "GDC": "file_name"
    }
  ],
  "byte_size": [
    {
      "PDC": "file_size",
      "GDC": "file_size"
    }
  ],
  "checksum": [
    {
      "PDC": "md5sum",
      "GDC": "md5sum"
    }
  ],
  "file_format": [
    {
      "PDC": "file_format",
      "GDC": "data_format"
    }
  ]
}
```

**R2 File fields and mappings**:

@druth314 and @kreinold can perhaps provide the extended JSON now that IDC data is included.

**Comment by druth314** [comment]
R2 File entity mappings:
`{
  "id": {
    "PDC": "file_id",
    "GDC": "file_id",
    "IDC": "crdc_instance_uuid"
  },
  "associated_project": {
    "PDC": "project_submitter_id",
    "GDC": "project.project_id",
    "IDC": "collection_id"
  },
  "data_category": {
    "PDC": "data_category",
    "GDC": "data_category",
    "IDC": 'Imaging'
  },
  "data_type": {
    "PDC": "file_type",
    "GDC": "data_type",
    "IDC": "Modality"
  },
  "label": {
    "PDC": "file_name",
    "GDC": "file_name",
    "IDC": 'SUBSTR(gcs_url, 15)'
  },
  "byte_size": {
    "PDC": "file_size",
    "GDC": "file_size",
    "IDC": null
  },
  "checksum": {
    "PDC": "md5sum",
    "GDC": "md5sum",
    "IDC": 'NULL'
  },
  "file_format": {
    "PDC": "file_format",
    "GDC": "data_format",
    "IDC": 'DICOM'
  },
  "drs_uri": {
    "PDC": 'format_drs(file_id)',
    "GDC": 'format_drs(file_id)',
    "IDC": gcs_url
  }
}
`
For clarification:
- IDC.data_category is the string 'Imaging' for all entries
- IDC.label uses a portion of the gcs_url. We use the SUBSTR() function in SQL to populate the field
- IDC.byte_size is a null integer type as no fields map from the IDC table we currently pull from
- IDC.checksum is a string NULL as no fields map from the IDC table we currently pull from
- IDC.file_format is the string 'DICOM' for all entries since all files in IDC are in DICOM format
- GDC.drs_uri and PDC.drs_uri use a custom function format_drs() and the file_id to create the drs_uri
- IDC.drs_uri is a misnomer, however identical schemas for File entities are required. As of now, no algorithmic way to construct drs_uri's from IDC data. Also the IDC data has not been indexed for drs_uri's

**Comment by YeastCell** [comment]
@druth314 This looks great! I would only suggest setting IDC.drs_uri to `null` since there is no DRS URI.

**Comment by druth314** [comment]
@elijahlowe 
Thank you so much for putting the code you used for this analysis. Under your present assumptions you would be correct that there is some disconnect, however there are files in GDC that are only associated with cases/ResearchSubjects and have no associations with any specimens. These are typically some clinical .xlsx files. Unfortunately this complicates things a bit, and you need to find the linkages from GDC as well to double check that the numbers are correct. As for PDC, their data model shows that all files are associated with aliquots so their number count looks fine.

**Comment by druth314** [comment]
@YeastCell and @elijahlowe I believe I have found the issue and it is in the aggregation code. GDC does not need to aggregate ResearchSubject level data since we do not have multiple instances of the same case being written in the extracted data. Thus when aggregating there is no issue. In PDC however since we are getting info by the study, and cases can be a part of more than one PDC study, we have multiple records of cases in the extracted PDC data. The aggregation code forgot to add File records for the ResearchSubjects that had to aggregate records together. I will alter it, and test this hypothesis with the aggregated PDC data(make BQ table of aggregated PDC data) Thank you both for finding this rather glaring flaw in the code.

**Comment by elijahlowe** [comment]
Yes, thanks @druth314 looks like you fixed the PDC bug. After talking with @YeastCell I better understand the duplicates at the Specimen level. While I do understand that the duplicates are because of the underlying nature of the data, I do believe we have to come up with a clear explanation for the end-users.


```
print("File: ", Counter(file_list['system']))
print("ResearchSubject.File: ", Counter(rs_file_list['system']))
print("ResearchSubject.Specimen.File: ", Counter(rs_s_file_list['system']))
print("ResearchSubject.Specimen.File (no dups): ", Counter(rs_s_file_list1['system']))

File:  Counter({'IDC': 191, 'PDC': 109, 'GDC': 54})
ResearchSubject.File:  Counter({'PDC': 109, 'GDC': 54})
ResearchSubject.Specimen.File:  Counter({'GDC': 266, 'PDC': 218})
ResearchSubject.Specimen.File (no dups):  Counter({'PDC': 109, 'GDC': 34})
```

**Comment by DavidPotCanuck** [comment]
or R2.x > R2.0

**Comment by fkaufman-asym** [comment]
This is finished and working
