### ISSUE TITLE
All types of specimens have Files

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#52]
In release 1, not all specimen types had files associated with them.

In release 2, these specimen types will now have files associated with them:

Outputs that users see of the file information are described in detail in this ticket (ticket x).

**Comment by druth314** [comment]
In R1: Only samples had a files associated with them. 
In R2: All specimens have (samples, portions, slides, analytes, aliquots)
The mapping of IDC fields to CDA is copied below:
File: {
"id": "crdc_instance_uuid"
"associated_project": "collection_id"
"data_category": 'Imaging'
"data_type": "Modality"
"label": 'SUBSTR(gcs_url, 15)'
"byte_size": null
"checksum": 'NULL'
"file_format": 'DICOM'
"drs_uri": gcs_url
}
For clarification:
- data_category is the string 'Imaging' for all entries
- label uses a portion of the gcs_url. We use the SUBSTR() function in SQL to populate the field
- byte_size is a null integer type as no fields map from the IDC table we currently pull from
- checksum is a string NULL as no fields map from the IDC table we currently pull from
- file_format is the string 'DICOM' for all entries since all files in IDC are in DICOM format
- drs_uri is a misnomer, however identical schemas for File entities are required. As of now, there is no algorithmic way to construct drs_uri's from IDC data. Also the IDC data has not been indexed for drs_uri's

**Comment by fkaufman-asym** [comment]
Documented as working
